### ISSUE TITLE
Cannot run any commands using retox

### ISSUE THREAD

**Issue by AlexArcPy** [tonybaloney/retox#29]
I have a Python 3.6 environment I've set up using `conda`. I've activated and done `pip install retox` into it. I am trying to set up the most simple layout to verify the `retox` is working. However, it looks as if it does not.

This is my `tox.ini` file:
```

[tox]
envlist = py36

[testenv]
basepython = 
	C:\Users\user\AppData\Local\Continuum\Anaconda2\envs\RetoxEnv\python.exe
commands = 
	{envpython} -m python -m unittest discover src/
```

When I run `retox` in the folder where I have my Python modules and the tests, I can see the blue screen with the information `[pass] Get environment` and the env is green. However, I see no output from the testing. I suspect that no commands are being executed.

The contents of `retox.log`:

```
System stdout encoding is utf-8
 
 ---- Starting new test run ----
Completing py36 with status 0
tox:   py36: commands succeeded
tox:   congratulations :)
tox: wrote json report at: C:\path\SampleFiles\.retox.json
```

Where should I look for hints?

**Comment by obestwalter** [comment]
Hi @AlexArcPy. I can't help you with your actual problem, but I am intereseted. Does that conda setup actually work if you use tox directly? I am not a conda user myself, but hear a lot that people would like conda support. There are some long standing issues about this and I have a vague idea from conversations with users what would need to be done to make it work (e.g. making some corners of tox pluggable to add conda specific functionality). So could you explain how and why this works with tox for you?

**Comment by AlexArcPy** [comment]
@obestwalter , thanks for mentioning the tox. I have run the `tox` command and it complained about the missing `setup.py`. I have found on the web that I had to use the 
```[tox]
skipsdist = True
```
in my `tox.ini` since I did not have any `setup.py` file. Then `tox` worked and `retox` also worked. 

The `conda` setup works fine for `tox`. I have a few `conda` envs I've created and using `tox` seems to be working fine. This is my `tox.ini` now.

```
[tox]
envlist = py36, py27
skipsdist = True

[testenv]
basepython = 
    py36: C:\Users\user\AppData\Local\Continuum\Anaconda2\envs\RetoxEnv\python.exe
	py27: C:\Users\user\AppData\Local\Continuum\Anaconda2\envs\GDBeePy27GDAL21\python.exe
	
commands = 
	{envpython} -m unittest discover src/
```

Does it help?
